"""Offline learning-from-demonstration building blocks."""

from .models import (
    DemonstrationTrajectory,
    FitResiduals,
    PoseSample,
    PreprocessingReport,
    PrimitiveFit,
    PrimitiveRecommendation,
    ProcessedTrajectory,
    SegmentationResult,
    SegmentationState,
    SegmentState,
    TimeInterval,
    TrajectorySample,
    TrajectorySegment,
)
from .path_simplification import (
    DEFAULT_PATH_SIMPLIFICATION_TOLERANCE_M,
    PathSimplificationProvenance,
    SimplifiedAnchorRelativePath,
    simplify_anchor_relative_path,
)
from .preprocessing import (
    PreprocessingConfig,
    TrajectoryPreprocessingError,
    preprocess_pose_samples,
    preprocess_trajectory,
)
from .primitive_fitter import (
    PeriodicPrimitiveGeometry,
    PrimitiveFitterConfig,
    PrimitiveFittingError,
    fit_arc,
    fit_line,
    fit_periodic,
    fit_periodic_primitive_geometry,
    recommend_primitive,
)
from .quality import (
    QualityAssessment,
    QualityConfig,
    RepeatConsistencyResult,
    assess_trajectory_quality,
    validate_repeat_consistency,
)
from .recorder import DemonstrationRecorder, load_demonstration, load_pose_samples
from .rgbd_dataset import (
    MediaPipeDatasetDiagnostic,
    RGBDDataset,
    RGBDDatasetManifest,
    RGBDDatasetSegmentation,
    RGBDDatasetValidationError,
    RGBDFrameArtifact,
    load_rgbd_dataset,
    mediapipe_dataset_diagnostic,
    segment_rgbd_dataset,
)
from .segmentation import SegmentationConfig, segment_trajectory
from .synthetic import (
    generate_arc_trajectory,
    generate_expert_wipe_trajectory,
    generate_line_trajectory,
    generate_novice_wipe_trajectory,
    generate_periodic_trajectory,
    generate_wipe_trajectory,
)

__all__ = [
    "DemonstrationRecorder",
    "DemonstrationTrajectory",
    "DEFAULT_PATH_SIMPLIFICATION_TOLERANCE_M",
    "FitResiduals",
    "PoseSample",
    "PathSimplificationProvenance",
    "PeriodicPrimitiveGeometry",
    "PreprocessingConfig",
    "PreprocessingReport",
    "PrimitiveFit",
    "PrimitiveFitterConfig",
    "PrimitiveFittingError",
    "PrimitiveRecommendation",
    "ProcessedTrajectory",
    "QualityAssessment",
    "QualityConfig",
    "RepeatConsistencyResult",
    "MediaPipeDatasetDiagnostic",
    "RGBDDataset",
    "RGBDDatasetManifest",
    "RGBDDatasetSegmentation",
    "RGBDDatasetValidationError",
    "RGBDFrameArtifact",
    "SegmentationConfig",
    "SegmentationResult",
    "SegmentationState",
    "SegmentState",
    "SimplifiedAnchorRelativePath",
    "TimeInterval",
    "TrajectorySegment",
    "TrajectoryPreprocessingError",
    "TrajectorySample",
    "assess_trajectory_quality",
    "fit_arc",
    "fit_line",
    "fit_periodic",
    "fit_periodic_primitive_geometry",
    "generate_arc_trajectory",
    "generate_expert_wipe_trajectory",
    "generate_line_trajectory",
    "generate_novice_wipe_trajectory",
    "generate_periodic_trajectory",
    "generate_wipe_trajectory",
    "load_demonstration",
    "load_pose_samples",
    "load_rgbd_dataset",
    "mediapipe_dataset_diagnostic",
    "preprocess_pose_samples",
    "preprocess_trajectory",
    "recommend_primitive",
    "segment_trajectory",
    "segment_rgbd_dataset",
    "simplify_anchor_relative_path",
    "validate_repeat_consistency",
]
