"""Bounded semantic drafting from chronological aligned RGB-D keyframes."""

from __future__ import annotations

from pathlib import Path

from openai import APIStatusError, OpenAI

from robot_skill_system.settings import OpenAIMode, Settings

from ._live import parse_structured_response
from .client import OpenAIClientFactory, RetryExecutor, new_trace_id
from .mock_client import MockOpenAIClient
from .schemas import (
    APICallMetadata,
    RecordingSkillDraft,
    RecordingSkillDraftInput,
)
from .semantic_validation import validate_recording_skill_draft

RECORDING_SKILL_INSTRUCTIONS = """Analyze chronological aligned RGB-D evidence for a robot
teaching recording and return only the strict schema. The JSON metadata is followed by exactly two
images for each keyframe index, always RGB first and its aligned depth colormap second. In the depth
colormap, nearer valid pixels are warmer and invalid pixels are black; use it only as qualitative
foreground/background and contact evidence, never as metric geometry.

The JSON may include local_hand_tracking generated by MediaPipe on the same RGB keyframe indices.
Use its selected wrist, thumb-tip, index, and palm landmarks as independent local evidence when
interpreting the images. Its x/y values are normalized image coordinates, while z_relative is a
non-metric MediaPipe ordering hint and must never be treated as depth, metres, or robot geometry.
Handedness is advisory because mirroring can swap its label. Do not convert this evidence into
poses or execution authority. If local tracking and the images disagree, retain the best visible
semantic observation and state the disagreement as an ambiguity. A completed frame with no hands
is a real local non-detection, while status=unavailable means only that the optional tracker could
not run.

The operator represents a two-jaw gripper with the thumb and index finger. Accept either an
empty-hand two-finger gesture OR a thumb-index pinch/grasp around a visible tool. The thumb and
index need not be straight or fully extended: if both distal fingertip/contact regions are visibly
and individually localizable on opposite sides of a tool handle, treat them as the two jaw tips.
A visible tool does not invalidate otherwise visible hand landmarks. Treat the visual TCP proxy as
the midpoint of those two hand landmarks; never substitute the tool shaft, tool tip, shadow, or a
fixture point for either fingertip.

Use tcp_proxy_definition.semantic_landmark_confidence_threshold from the request as the explicit
landmark decision threshold. This is deliberately a relaxed semantic-observation threshold, not an
execution confidence threshold. When both thumb/index skin endpoints or handle-contact centers are
anatomically plausible at or above that threshold, set landmarks_detected=true and return the best
normalized points with the actual confidence. Do not require high confidence or complete fingertip
contours. Express partial occlusion and overlap by lowering confidence instead of withholding
points. Use null points only when either hand landmark is below the requested threshold or no
plausible skin region is visible. The local system applies a separate, stricter trajectory-quality
gate before any candidate geometry can be trusted.

First find the hand ROI, identify thumb versus index using hand anatomy and adjacent frames, then
audit every frame in chronological order. Use temporal continuity to preserve landmark identity,
but never copy a coordinate into an occluded frame. Return exactly one observed_states item for
EVERY supplied keyframe. When both hand landmarks are visible, return normalized [0,1] image
positions for tip A, tip B, and their midpoint. When either landmark cannot be localized separately
from the tool or other fingers, set landmarks_detected=false, set all three positions to null,
classify the state as occluded or uncertain, and explain the failure. Classify the scene hand as
two_finger_gripper when a dominant thumb-index pinch is visible even if the remaining fingers are
curled; use closed_hand only when no opposed thumb-index pair can be individually localized. Audit
the whole sequence with trajectory_status, valid_landmark_frame_count,
usable_for_local_depth_path, and an explicit failure_reason whenever fewer than four frames contain
valid landmark pairs. usable_for_local_depth_path is a recommendation, not another detection flag:
it may remain false even with four or more detected frames when overlap, depth, or temporal quality
is too weak for local reconstruction. In that case keep the detected coordinates, set an explicit
failure_reason, and let local code report the low-confidence evidence without failing the semantic
draft.

Also return scene_observation for the person's hand shape, tool shape, and workbench/work-surface
shape. For each item choose a representative supplied frame and a normalized image region when it
is visible. Work-surface output is a semantic ROI and plane-likelihood hint only. Local code will
re-open raw aligned depth and calibrated intrinsics to estimate metric geometry.

Suggest only operations and entity roles present in the supplied catalogs. Never invent
coordinates, poses, transforms, speed, acceleration, force, code, robot calls, or execution
permission. RGB-D images and the two-finger proxy contain no trusted robot-base trajectory or TF,
so executable must remain false, requires_pose_trajectory must remain true,
tcp_proxy_observation.semantic_only must remain true, and robot_tcp_pose_available must remain
false. Normalized image locations are not robot coordinates. Do not output camera coordinates,
metric depth, robot poses, or metric transforms. State important visual ambiguity explicitly."""

RECORDING_PDF_FALLBACK_INSTRUCTIONS = """Analyze the chronological RGB-D contact-sheet PDF as
evidence for a robot teaching recording and return only the strict schema. Each RGB image is paired
with its aligned depth colormap and labeled with the original frame index. Nearer valid depth pixels
are warmer and invalid pixels are black. The JSON may also include local_hand_tracking from
MediaPipe on those same RGB indices. Its normalized x/y selected landmarks are independent
semantic evidence; z_relative is non-metric and handedness is advisory. Never turn this local
evidence into depth, camera/robot poses, or execution authority. Preserve any disagreement between
the PDF and local tracker as an ambiguity. The operator represents a gripper with the thumb and
index finger. Accept an empty-hand gesture or a thumb-index pinch around a tool; the fingers need
not be straight. If both distal fingertip/contact regions are separately visible on opposite sides
of a tool handle, treat them as jaw tips and their midpoint as a qualitative TCP proxy. Never
substitute the tool shaft or tool tip for a hand landmark. Use adjacent frames to preserve
thumb/index identity, but never invent coordinates through occlusion. Apply the request's
tcp_proxy_definition.semantic_landmark_confidence_threshold as a relaxed semantic threshold. At or
above it, return the best anatomically plausible hand points and actual confidence even under
partial overlap; do not require complete fingertip contours. This does not grant execution
authority, and local code applies a stricter trajectory-quality gate. Return one audited state for
EVERY labeled keyframe. When both hand landmarks meet the threshold, output their normalized [0,1]
image positions and midpoint; otherwise use null positions and an explicit failure reason. Classify
a dominant visible thumb-index pinch as two_finger_gripper even when other fingers are curled.
usable_for_local_depth_path may be false despite four or more detected frames when reconstruction
quality is weak; preserve the coordinates and explain that recommendation in failure_reason.
Return hand, tool, and work-surface shapes with representative frame indices and normalized regions
as semantic hints for local raw-depth processing. Never output camera coordinates, metric depth,
poses, transforms,
speed, acceleration, force, code, robot calls, or execution permission. Suggest only catalog roles
and operations. The PDF contains no trusted robot-base trajectory or TF, so executable must remain
false, requires_pose_trajectory and tcp_proxy_observation.semantic_only must remain true, and
robot_tcp_pose_available must remain false. State important visual ambiguity explicitly."""


class ImageInputRejectedError(RuntimeError):
    """The provider rejected the direct image payload and a file fallback may be attempted."""


class RecordingSkillDraftAnalyzer:
    """Create a semantic draft; local code remains responsible for all executable geometry."""

    def __init__(
        self,
        settings: Settings,
        *,
        client: OpenAI | None = None,
        mock: MockOpenAIClient | None = None,
        retry: RetryExecutor | None = None,
    ) -> None:
        self.settings = settings
        self._client = client
        self._mock = mock or MockOpenAIClient()
        self._retry = retry or RetryExecutor(settings.openai_api_max_retries)

    def analyze(
        self,
        request: RecordingSkillDraftInput,
        *,
        rgb_paths: list[Path],
        depth_paths: list[Path],
    ) -> tuple[RecordingSkillDraft, APICallMetadata]:
        """Analyze checksum-verified RGB-depth pairs without client-selected paths."""

        if len(rgb_paths) != len(request.keyframe_indices) or len(depth_paths) != len(
            request.keyframe_indices
        ):
            raise ValueError("RGB, depth, and keyframe indices must have the same length")
        if len(rgb_paths) > self.settings.openai_max_keyframes:
            raise ValueError("keyframe count exceeds the configured OpenAI bound")
        if any(not path.is_file() for path in [*rgb_paths, *depth_paths]):
            raise ValueError("every selected RGB-D keyframe must be a local file")
        image_paths = [
            path
            for rgb_path, depth_path in zip(rgb_paths, depth_paths, strict=True)
            for path in (rgb_path, depth_path)
        ]

        trace_id = new_trace_id()
        if self.settings.openai_mode is OpenAIMode.MOCK:
            draft, metadata = self._mock.analyze_recording_skill_draft(request, trace_id)
        else:
            client = self._client or OpenAIClientFactory(self.settings).create()
            try:
                draft, metadata = parse_structured_response(
                    client=client,
                    retry=self._retry,
                    model=self.settings.openai_reasoning_model,
                    instructions=RECORDING_SKILL_INSTRUCTIONS,
                    payload=request,
                    output_type=RecordingSkillDraft,
                    trace_id=trace_id,
                    image_paths=image_paths,
                    image_detail=self.settings.openai_image_detail,
                )
            except APIStatusError as exc:
                if _is_image_input_rejection(exc):
                    raise ImageInputRejectedError(
                        "OpenAI rejected the direct RGB-D image payload"
                    ) from exc
                raise
        self._validate_draft(draft, request)
        return draft, metadata

    def analyze_pdf(
        self,
        request: RecordingSkillDraftInput,
        *,
        contact_sheet_path: Path,
    ) -> tuple[RecordingSkillDraft, APICallMetadata]:
        """Analyze a locally generated PDF when the provider rejects direct images."""

        if contact_sheet_path.suffix.lower() != ".pdf" or not contact_sheet_path.is_file():
            raise ValueError("contact-sheet fallback must be an existing PDF")
        trace_id = new_trace_id()
        if self.settings.openai_mode is OpenAIMode.MOCK:
            draft, metadata = self._mock.analyze_recording_skill_draft(request, trace_id)
        else:
            client = self._client or OpenAIClientFactory(self.settings).create()
            draft, metadata = parse_structured_response(
                client=client,
                retry=self._retry,
                model=self.settings.openai_reasoning_model,
                instructions=RECORDING_PDF_FALLBACK_INSTRUCTIONS,
                payload=request,
                output_type=RecordingSkillDraft,
                trace_id=trace_id,
                file_paths=[contact_sheet_path],
                image_detail=self.settings.openai_image_detail,
            )
        self._validate_draft(draft, request)
        return draft, metadata

    @staticmethod
    def _validate_draft(
        draft: RecordingSkillDraft,
        request: RecordingSkillDraftInput,
    ) -> None:
        validate_recording_skill_draft(
            draft,
            primitive_catalog=request.primitive_catalog,
            entity_role_catalog=request.entity_role_catalog,
            keyframe_indices=request.keyframe_indices,
        )


def _is_image_input_rejection(exc: APIStatusError) -> bool:
    if exc.status_code in {413, 415, 422}:
        return True
    if exc.status_code != 400:
        return False
    message = str(exc).lower()
    return any(
        marker in message
        for marker in (
            "image",
            "input_image",
            "payload too large",
            "request too large",
            "unsupported media",
        )
    )


__all__ = ["ImageInputRejectedError", "RecordingSkillDraftAnalyzer"]
